apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
        - name: socket-server
          image: socket_server:0.1.0
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: socket-server-service
spec:
  selector:
    app: socket-server
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: NodePort
